FROM grafana/grafana:latest

USER root

# Criar os diretórios necessários
RUN mkdir /var/lib/grafana/dashboards

# Copiar os arquivos de provisionamento e dashboards
COPY provisioning/datasource.yml /etc/grafana/provisioning/datasources/
COPY provisioning/dashboard.yml /etc/grafana/provisioning/dashboards/
COPY dashboards/mariadb_dashboard.json /var/lib/grafana/dashboards/

# Ajustar permissões para o usuário grafana
RUN chown -R 472:472 /etc/grafana/provisioning

USER grafana
