# Dockerfile (Flask AppBuilder)
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

#COPY . .
COPY app.py /app/

# Copiar também o arquivo de teste test_app.py
COPY test_app.py /app/

CMD ["flask", "run", "--host=0.0.0.0"]
